"""
config.py — Loads and validates all configuration.
Supports three modes:
  Terminal / SKILL  →  load()            reads .env + yaml files
  API               →  load_from_dict()  reads request body dict
"""
import os
import re
import shutil
import uuid
from datetime import datetime
from pathlib import Path
from dataclasses import dataclass, field
from typing import List, Optional, Set, Dict, Any


@dataclass
class ServiceConfig:
    name: str
    path: str
    api_paths: List[str] = field(default_factory=lambda: ["."])


@dataclass
class TargetEndpoint:
    path: str
    method: str = "ANY"
    label: str = ""
    acl_priority: str = "HIGH"
    service_name: Optional[str] = None


# Valid skip keys
SKIP_OPTIONS = {
    "docs":      "Skip markdown API docs (documents/)",
    "datamodel": "Skip Mermaid class diagrams (data_model/)",
    "er":        "Skip ER diagrams (db_entity_relations/)",
    "postman":   "Skip Postman collections (postman_collection/)",
    "swagger":   "Skip OpenAPI YAML (api_document/)",
}

# Supported VCS providers
VCS_PROVIDERS = ("github", "gitlab", "azure", "bitbucket")


@dataclass
class Config:
    # Run identity
    run_id: str            # unique per run — scopes all workspace paths

    # Repo
    service: str
    repo: str
    branch: str
    repo_root: str         # workspace/runs/<run_id>/repos/<service>

    # Monorepo
    is_monorepo: bool
    services: List[ServiceConfig]

    # VCS
    vcs_provider: str      # github | gitlab | azure | bitbucket
    vcs_token: str         # provider-specific token
    vcs_base_url: str      # for self-hosted: e.g. https://git.company.com

    # Claude / Anthropic
    api_key: str           # ANTHROPIC_API_KEY — empty = use Claude Code CLI
    claude_bin: str        # path to claude CLI
    claude_model: str
    parallel_workers: int

    # What to skip
    skip: Set[str]

    # PR
    raise_pr: bool         # whether to raise a PR after generation
    pr_base_branch: str    # branch to PR into (defaults to clone branch)

    # Endpoints
    target_endpoints: List[TargetEndpoint]

    # Workspace paths (all scoped under run_id)
    project_root: str
    run_dir: str           # workspace/runs/<run_id>
    analysis_dir: str
    manifests_dir: str

    # Output paths
    output_dir: str
    docs_dir: str
    data_model_dir: str
    db_er_dir: str
    postman_dir: str
    api_doc_dir: str


# ─── Helpers ──────────────────────────────────────────────────────────────────

def _find_claude() -> str:
    found = shutil.which("claude")
    if found:
        return found
    for c in [
        os.path.expanduser("~/.local/bin/claude"),
        "/usr/local/bin/claude",
        "/opt/homebrew/bin/claude",
    ]:
        if os.path.isfile(c) and os.access(c, os.X_OK):
            return c
    return "claude"


def _strip_comments(content: str) -> str:
    return '\n'.join(
        line for line in content.splitlines()
        if not line.strip().startswith('#')
    )


def _parse_list(content: str, key: str) -> List[str]:
    pattern = rf'{re.escape(key)}:\s*\n((?:\s+-[^\n]+\n?)*)'
    match = re.search(pattern, content)
    if not match:
        return []
    return [re.sub(r'^\s*-\s*', '', l).strip()
            for l in match.group(1).splitlines()
            if l.strip().startswith('-')]


def _make_run_id(mode: str = "terminal") -> str:
    """
    Terminal/SKILL: timestamp-based  →  20250516_143022
    API:            UUID short       →  generated by run_manager, passed in
    """
    return datetime.now().strftime("%Y%m%d_%H%M%S")


def _build_paths(project_root: str, service: str, run_id: str) -> dict:
    """Build all workspace and output paths scoped under run_id."""
    run_dir      = os.path.join(project_root, "workspace", "runs", run_id)
    repo_root    = os.path.join(run_dir, "repos", service)
    analysis_dir = os.path.join(run_dir, "analysis")
    manifests_dir = os.path.join(run_dir, "manifests")
    output_dir   = os.path.join(run_dir, "output")

    paths = {
        "run_dir":       run_dir,
        "repo_root":     repo_root,
        "analysis_dir":  analysis_dir,
        "manifests_dir": manifests_dir,
        "output_dir":    output_dir,
        "docs_dir":      os.path.join(output_dir, "documents"),
        "data_model_dir": os.path.join(output_dir, "data_model"),
        "db_er_dir":     os.path.join(output_dir, "db_entity_relations"),
        "postman_dir":   os.path.join(output_dir, "postman_collection"),
        "api_doc_dir":   os.path.join(output_dir, "api_document"),
    }

    for d in paths.values():
        os.makedirs(d, exist_ok=True)

    return paths


def _parse_services(content: str, repo_root: str,
                    is_mono: bool, service: str) -> List[ServiceConfig]:
    services = []
    if is_mono:
        name_matches = re.findall(r'- name:\s*(\S+)', content)
        path_matches = re.findall(r'  path:\s*(\S+)', content)
        if not name_matches:
            raise ValueError(
                "IS_MONOREPO=true but no services defined in config/repos.yaml.\n"
                "Add a services block:\n\n"
                "  repo:\n"
                "    services:\n"
                "      - name: auth-service\n"
                "        path: services/auth-service\n"
            )
        for i, name in enumerate(name_matches):
            svc_path = os.path.join(repo_root, path_matches[i]) \
                       if i < len(path_matches) else repo_root
            services.append(ServiceConfig(name=name, path=svc_path))
    else:
        api_paths = _parse_list(content, "api_paths") or ["."]
        services.append(ServiceConfig(
            name=service, path=repo_root, api_paths=api_paths
        ))
    return services


def _parse_target_endpoints(content: str) -> List[TargetEndpoint]:
    paths     = re.findall(r'path:\s*"([^"]+)"', content)
    methods   = re.findall(r'method:\s*(\S+)',    content)
    labels    = re.findall(r'label:\s*"([^"]+)"', content)
    prios     = re.findall(r'acl_priority:\s*(\S+)', content)
    svc_names = re.findall(r'service_name:\s*(\S+)', content)

    endpoints = []
    for i, path in enumerate(paths):
        endpoints.append(TargetEndpoint(
            path=path,
            method=methods[i]      if i < len(methods)    else "ANY",
            label=labels[i]        if i < len(labels)     else "",
            acl_priority=prios[i]  if i < len(prios)      else "HIGH",
            service_name=svc_names[i] if i < len(svc_names) else None,
        ))
    return endpoints


# ─── Terminal / SKILL mode ────────────────────────────────────────────────────

def load(project_root: str = ".",
         skip: Optional[Set[str]] = None,
         run_id: Optional[str] = None) -> Config:
    """Load config from .env and yaml files (Terminal / SKILL mode)."""
    project_root = str(Path(project_root).resolve())
    skip   = skip or set()
    run_id = run_id or _make_run_id()

    # ── .env ──────────────────────────────────────────────────────────────
    env = {}
    env_path = os.path.join(project_root, ".env")
    if os.path.exists(env_path):
        with open(env_path) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    k, _, v = line.partition('=')
                    env[k.strip()] = v.strip()

    service  = env.get("SERVICE", "")
    repo     = env.get("REPO", "")
    branch   = env.get("BRANCH", "main")
    is_mono  = env.get("IS_MONOREPO", "false").lower() == "true"
    model    = env.get("CLAUDE_MODEL", "")
    workers  = int(env.get("PARALLEL_WORKERS", "4"))
    api_key  = env.get("ANTHROPIC_API_KEY", "") or os.environ.get("ANTHROPIC_API_KEY", "")

    # VCS
    vcs_provider = env.get("VCS_PROVIDER", "github").lower()
    vcs_token    = (
        env.get("GITHUB_TOKEN") or env.get("GITLAB_TOKEN") or
        env.get("AZURE_TOKEN")  or env.get("BITBUCKET_TOKEN") or ""
    )
    # Per-provider token override
    token_key = {"github": "GITHUB_TOKEN", "gitlab": "GITLAB_TOKEN",
                 "azure": "AZURE_TOKEN", "bitbucket": "BITBUCKET_TOKEN"}
    vcs_token    = env.get(token_key.get(vcs_provider, ""), vcs_token)
    vcs_base_url = env.get("VCS_BASE_URL", "")

    # PR
    raise_pr      = env.get("RAISE_PR", "false").lower() == "true"
    pr_base_branch = env.get("PR_BASE_BRANCH", branch)

    if not api_key:
        print("ℹ️  ANTHROPIC_API_KEY not set — using Claude Code CLI (token tracking disabled)")

    if not service:
        raise ValueError("SERVICE not set in .env")
    if not repo:
        raise ValueError("REPO not set in .env")

    # ── Paths ──────────────────────────────────────────────────────────────
    paths = _build_paths(project_root, service, run_id)
    repo_root = paths["repo_root"]

    # ── repos.yaml ────────────────────────────────────────────────────────
    repos_yaml = os.path.join(project_root, "config", "repos.yaml")
    if os.path.exists(repos_yaml):
        with open(repos_yaml) as f:
            content = _strip_comments(f.read())
        services = _parse_services(content, repo_root, is_mono, service)
    else:
        services = [ServiceConfig(name=service, path=repo_root)]

    # ── target-endpoints.yaml ──────────────────────────────────────────────
    targets_yaml = os.path.join(project_root, "config", "target-endpoints.yaml")
    target_endpoints = []
    if os.path.exists(targets_yaml):
        with open(targets_yaml) as f:
            content = _strip_comments(f.read())
        target_endpoints = _parse_target_endpoints(content)

    return Config(
        run_id=run_id,
        service=service, repo=repo, branch=branch,
        repo_root=repo_root,
        is_monorepo=is_mono, services=services,
        vcs_provider=vcs_provider, vcs_token=vcs_token, vcs_base_url=vcs_base_url,
        api_key=api_key, claude_bin=_find_claude(),
        claude_model=model, parallel_workers=workers,
        skip=skip, target_endpoints=target_endpoints,
        raise_pr=raise_pr, pr_base_branch=pr_base_branch,
        project_root=project_root,
        run_dir=paths["run_dir"],
        analysis_dir=paths["analysis_dir"],
        manifests_dir=paths["manifests_dir"],
        output_dir=paths["output_dir"],
        docs_dir=paths["docs_dir"],
        data_model_dir=paths["data_model_dir"],
        db_er_dir=paths["db_er_dir"],
        postman_dir=paths["postman_dir"],
        api_doc_dir=paths["api_doc_dir"],
    )


# ─── API mode ─────────────────────────────────────────────────────────────────

def load_from_dict(data: Dict[str, Any],
                   project_root: str = ".",
                   run_id: Optional[str] = None) -> Config:
    """
    Load config from a request body dict (API mode).
    No .env or yaml files read — everything comes from the request.
    """
    project_root = str(Path(project_root).resolve())
    run_id = run_id or str(uuid.uuid4())[:8]

    service  = data.get("service", "")
    repo     = data.get("repo", "")
    branch   = data.get("branch", "main")
    is_mono  = data.get("is_monorepo", False)
    model    = data.get("claude_model", "")
    workers  = int(data.get("parallel_workers", 4))
    api_key  = data.get("anthropic_api_key", "") or os.environ.get("ANTHROPIC_API_KEY", "")
    skip     = set(data.get("skip", []))

    # VCS
    vcs_provider = data.get("vcs_provider", "github").lower()
    vcs_token    = data.get("vcs_token", "")
    vcs_base_url = data.get("vcs_base_url", "")

    # PR
    raise_pr       = data.get("raise_pr", False)
    pr_base_branch = data.get("pr_base_branch", branch)

    if not service:
        raise ValueError("'service' is required in request body")
    if not repo:
        raise ValueError("'repo' is required in request body")

    paths     = _build_paths(project_root, service, run_id)
    repo_root = paths["repo_root"]

    # Services — from request body or default to single service
    raw_services = data.get("services", [])
    if is_mono and raw_services:
        services = [
            ServiceConfig(
                name=s["name"],
                path=os.path.join(repo_root, s.get("path", s["name"])),
                api_paths=s.get("api_paths", ["."]),
            )
            for s in raw_services
        ]
    else:
        services = [ServiceConfig(name=service, path=repo_root)]

    # Target endpoints — from request body
    raw_eps = data.get("target_endpoints", [])
    target_endpoints = [
        TargetEndpoint(
            path=ep["path"],
            method=ep.get("method", "ANY"),
            label=ep.get("label", ""),
            acl_priority=ep.get("acl_priority", "HIGH"),
            service_name=ep.get("service_name"),
        )
        for ep in raw_eps
    ]

    return Config(
        run_id=run_id,
        service=service, repo=repo, branch=branch,
        repo_root=repo_root,
        is_monorepo=is_mono, services=services,
        vcs_provider=vcs_provider, vcs_token=vcs_token, vcs_base_url=vcs_base_url,
        api_key=api_key, claude_bin=_find_claude(),
        claude_model=model, parallel_workers=workers,
        skip=skip, target_endpoints=target_endpoints,
        raise_pr=raise_pr, pr_base_branch=pr_base_branch,
        project_root=project_root,
        run_dir=paths["run_dir"],
        analysis_dir=paths["analysis_dir"],
        manifests_dir=paths["manifests_dir"],
        output_dir=paths["output_dir"],
        docs_dir=paths["docs_dir"],
        data_model_dir=paths["data_model_dir"],
        db_er_dir=paths["db_er_dir"],
        postman_dir=paths["postman_dir"],
        api_doc_dir=paths["api_doc_dir"],
    )
