"""
pr.py — Raise a Pull/Merge Request via the VCS provider REST API.
Uses httpx — no third-party VCS SDK dependencies.
Supports: GitHub, GitLab (cloud + self-hosted), Azure Repos, Bitbucket.
"""
import re
from datetime import datetime
from typing import Optional
import httpx

from config import Config


# ─── PR body builder ──────────────────────────────────────────────────────────

def _build_pr_body(cfg: Config, endpoints_documented: list) -> str:
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        f"## 🩺 Doctor — API Documentation",
        f"",
        f"**Service:** `{cfg.service}`  ",
        f"**Run ID:** `{cfg.run_id}`  ",
        f"**Generated:** {now}",
        f"",
        f"### Endpoints Documented ({len(endpoints_documented)})",
        f"",
    ]
    for ep in endpoints_documented:
        method = ep.get("method", "")
        path   = ep.get("path", "")
        label  = ep.get("label", "")
        suffix = f" — {label}" if label else ""
        lines.append(f"- `{method}` `{path}`{suffix}")

    lines += [
        f"",
        f"### Output",
        f"",
        f"| Artifact | Location |",
        f"|---|---|",
        f"| API Docs | `docs/doctor/{cfg.service}/documents/` |",
        f"| Data Model Charts | `docs/doctor/{cfg.service}/data_model/` |",
        f"| ER Diagram | `docs/doctor/{cfg.service}/db_entity_relations/` |",
        f"| Postman Collection | `docs/doctor/{cfg.service}/postman_collection/` |",
        f"| OpenAPI YAML | `docs/doctor/{cfg.service}/api_document/` |",
        f"",
        f"---",
        f"_Auto-generated by [Doctor](https://github.com/mahulivishal/doctor)_",
    ]
    return "\n".join(lines)


# ─── URL parsing ──────────────────────────────────────────────────────────────

def _parse_repo_info(cfg: Config) -> dict:
    """Extract owner, repo name, org etc. from the repo URL."""
    url = cfg.repo.rstrip(".git")

    if cfg.vcs_provider == "github":
        m = re.search(r'github\.com[/:](.+?)/(.+?)(?:\.git)?$', url)
        if m:
            return {"owner": m.group(1), "repo": m.group(2)}

    if cfg.vcs_provider == "gitlab":
        base = cfg.vcs_base_url or "https://gitlab.com"
        path = url.replace(base, "").strip("/")
        parts = path.split("/")
        return {
            "namespace": "/".join(parts[:-1]),
            "project":   parts[-1],
            "full_path": path,
        }

    if cfg.vcs_provider == "azure":
        # https://dev.azure.com/{org}/{project}/_git/{repo}
        m = re.search(r'dev\.azure\.com/([^/]+)/([^/]+)/_git/([^/]+)', url)
        if m:
            return {"org": m.group(1), "project": m.group(2), "repo": m.group(3)}

    if cfg.vcs_provider == "bitbucket":
        m = re.search(r'bitbucket\.org/([^/]+)/([^/]+)', url)
        if m:
            return {"workspace": m.group(1), "repo": m.group(2)}

    return {}


# ─── Provider implementations ─────────────────────────────────────────────────

async def _github_pr(cfg: Config, head: str, title: str, body: str) -> str:
    info = _parse_repo_info(cfg)
    url  = f"https://api.github.com/repos/{info['owner']}/{info['repo']}/pulls"

    async with httpx.AsyncClient() as client:
        r = await client.post(
            url,
            headers={
                "Authorization": f"Bearer {cfg.vcs_token}",
                "Accept":        "application/vnd.github+json",
                "X-GitHub-Api-Version": "2022-11-28",
            },
            json={
                "title": title,
                "body":  body,
                "head":  head,
                "base":  cfg.pr_base_branch,
            },
            timeout=30,
        )
        r.raise_for_status()
        return r.json().get("html_url", "")


async def _gitlab_pr(cfg: Config, head: str, title: str, body: str) -> str:
    base_url  = (cfg.vcs_base_url or "https://gitlab.com").rstrip("/")
    info      = _parse_repo_info(cfg)
    full_path = info.get("full_path", "")
    # GitLab needs URL-encoded project path
    encoded   = full_path.replace("/", "%2F")
    url       = f"{base_url}/api/v4/projects/{encoded}/merge_requests"

    async with httpx.AsyncClient() as client:
        r = await client.post(
            url,
            headers={"PRIVATE-TOKEN": cfg.vcs_token},
            json={
                "title":         title,
                "description":   body,
                "source_branch": head,
                "target_branch": cfg.pr_base_branch,
            },
            timeout=30,
        )
        r.raise_for_status()
        return r.json().get("web_url", "")


async def _azure_pr(cfg: Config, head: str, title: str, body: str) -> str:
    info    = _parse_repo_info(cfg)
    org     = info.get("org", "")
    project = info.get("project", "")
    repo    = info.get("repo", "")
    url     = (
        f"https://dev.azure.com/{org}/{project}/_apis/git/repositories/"
        f"{repo}/pullrequests?api-version=7.1"
    )

    import base64
    encoded_token = base64.b64encode(f":{cfg.vcs_token}".encode()).decode()

    async with httpx.AsyncClient() as client:
        r = await client.post(
            url,
            headers={
                "Authorization": f"Basic {encoded_token}",
                "Content-Type":  "application/json",
            },
            json={
                "title":         title,
                "description":   body,
                "sourceRefName": f"refs/heads/{head}",
                "targetRefName": f"refs/heads/{cfg.pr_base_branch}",
            },
            timeout=30,
        )
        r.raise_for_status()
        pr_id = r.json().get("pullRequestId", "")
        return (
            f"https://dev.azure.com/{org}/{project}/_git/{repo}"
            f"/pullrequest/{pr_id}"
        )


async def _bitbucket_pr(cfg: Config, head: str, title: str, body: str) -> str:
    info = _parse_repo_info(cfg)
    url  = (
        f"https://api.bitbucket.org/2.0/repositories/"
        f"{info['workspace']}/{info['repo']}/pullrequests"
    )

    async with httpx.AsyncClient() as client:
        r = await client.post(
            url,
            headers={
                "Authorization": f"Bearer {cfg.vcs_token}",
                "Content-Type":  "application/json",
            },
            json={
                "title":       title,
                "description": body,
                "source":      {"branch": {"name": head}},
                "destination": {"branch": {"name": cfg.pr_base_branch}},
            },
            timeout=30,
        )
        r.raise_for_status()
        return r.json().get("links", {}).get("html", {}).get("href", "")


# ─── Public entry point ───────────────────────────────────────────────────────

async def raise_pr(cfg: Config,
                   branch_name: str,
                   endpoints_documented: list) -> str:
    """
    Raise a PR/MR on the configured VCS provider.
    Returns the PR URL.
    """
    title = f"Doctor: API docs for {cfg.service} [{cfg.run_id}]"
    body  = _build_pr_body(cfg, endpoints_documented)

    print(f"\n🔀 Raising PR on {cfg.vcs_provider}...")
    print(f"   Branch: {branch_name} → {cfg.pr_base_branch}")

    provider_map = {
        "github":    _github_pr,
        "gitlab":    _gitlab_pr,
        "azure":     _azure_pr,
        "bitbucket": _bitbucket_pr,
    }

    fn = provider_map.get(cfg.vcs_provider)
    if not fn:
        raise ValueError(
            f"Unsupported VCS provider: {cfg.vcs_provider}. "
            f"Valid: {list(provider_map.keys())}"
        )

    try:
        pr_url = await fn(cfg, branch_name, title, body)
        print(f"✅ PR created: {pr_url}")
        return pr_url
    except httpx.HTTPStatusError as e:
        raise RuntimeError(
            f"PR creation failed ({e.response.status_code}): "
            f"{e.response.text[:300]}"
        ) from e
